# Generated by Django 5.2.9 on 2026-01-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
