# Generated by Django 5.2.9 on 2026-01-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(to="quote.tag"),
        ),
    ]
