# Generated by Django 5.2.9 on 2026-01-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0003_tag_unique_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="counter",
            field=models.IntegerField(default=0),
        ),
    ]
